/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Member {
  'id' : bigint,
  'accessLevel' : bigint,
  'joinYear' : bigint,
  'name' : string,
  'role' : string,
}
export interface Project {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'year' : bigint,
  'description' : string,
}
export interface UpcomingProject {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'progress' : bigint,
  'expectedYear' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<
    [bigint, string, string, bigint, bigint],
    undefined
  >,
  'addProject' : ActorMethod<
    [bigint, string, string, bigint, string],
    undefined
  >,
  'addUpcomingProject' : ActorMethod<
    [bigint, string, string, bigint, bigint],
    undefined
  >,
  'addWishlist' : ActorMethod<[], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAllUpcomingProjects' : ActorMethod<[], Array<UpcomingProject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClubInfo' : ActorMethod<
    [],
    { 'version' : string, 'foundingYear' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorCount' : ActorMethod<[], bigint>,
  'getWishlistCount' : ActorMethod<[], bigint>,
  'incrementVisitor' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isProjectRevealed' : ActorMethod<[], boolean>,
  'isWishlisted' : ActorMethod<[], boolean>,
  'removeWishlist' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];