/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'accessLevel' : IDL.Nat,
  'joinYear' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
});
export const UpcomingProject = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'expectedYear' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'addUpcomingProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addWishlist' : IDL.Func([], [IDL.Bool], []),
  'addWishlistAnon' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAllUpcomingProjects' : IDL.Func(
      [],
      [IDL.Vec(UpcomingProject)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClubInfo' : IDL.Func(
      [],
      [IDL.Record({ 'version' : IDL.Text, 'foundingYear' : IDL.Nat })],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getWishlistCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisitor' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isProjectRevealed' : IDL.Func([], [IDL.Bool], ['query']),
  'isWishlisted' : IDL.Func([], [IDL.Bool], ['query']),
  'isWishlistedAnon' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'removeWishlist' : IDL.Func([], [IDL.Bool], []),
  'removeWishlistAnon' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'accessLevel' : IDL.Nat,
    'joinYear' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
  });
  const UpcomingProject = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'expectedYear' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'addUpcomingProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addWishlist' : IDL.Func([], [IDL.Bool], []),
    'addWishlistAnon' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAllUpcomingProjects' : IDL.Func(
        [],
        [IDL.Vec(UpcomingProject)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClubInfo' : IDL.Func(
        [],
        [IDL.Record({ 'version' : IDL.Text, 'foundingYear' : IDL.Nat })],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getWishlistCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisitor' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isProjectRevealed' : IDL.Func([], [IDL.Bool], ['query']),
    'isWishlisted' : IDL.Func([], [IDL.Bool], ['query']),
    'isWishlistedAnon' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'removeWishlist' : IDL.Func([], [IDL.Bool], []),
    'removeWishlistAnon' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };